
DEPENDENCIES_ := $(foreach DEPENDENCY,$(DEPENDENCIES),$(ROOT)$(DEPENDENCY)/dependencies.pri)
DEPENDENCIES = 
include $(DEPENDENCIES_)

DEPENDENCIES_ := $(foreach DEPENDENCY,$(DEPENDENCIES),$(ROOT)$(DEPENDENCY)/dependencies.pri)
DEPENDENCIES = 
include $(DEPENDENCIES_)

DEPENDENCIES_ := $(foreach DEPENDENCY,$(DEPENDENCIES),$(ROOT)$(DEPENDENCY)/dependencies.pri)
DEPENDENCIES = 
include $(DEPENDENCIES_)

DEPENDENCIES_ := $(foreach DEPENDENCY,$(DEPENDENCIES),$(ROOT)$(DEPENDENCY)/dependencies.pri)
DEPENDENCIES = 
include $(DEPENDENCIES_)

DEPENDENCIES_ := $(foreach DEPENDENCY,$(DEPENDENCIES),$(ROOT)$(DEPENDENCY)/dependencies.pri)
DEPENDENCIES = 
include $(DEPENDENCIES_)

DEPENDENCIES_ := $(foreach DEPENDENCY,$(DEPENDENCIES),$(ROOT)$(DEPENDENCY)/dependencies.pri)
DEPENDENCIES = 
include $(DEPENDENCIES_)

DEPENDENCIES_ := $(foreach DEPENDENCY,$(DEPENDENCIES),$(ROOT)$(DEPENDENCY)/dependencies.pri)
DEPENDENCIES = 
include $(DEPENDENCIES_)

