
string(REGEX REPLACE "TMP123_" "" TP_STATIC_INIT "${TP_STATIC_INIT}")

file(WRITE tp_static_init.cpp [=[
//Generated by "static_init_generator.cmake" script

]=])

foreach(f ${TP_STATIC_INIT})

  set(out_cpp_text [=[
#include "{2}/Globals.h"

extern int {2}_staticInit;
int {2}_staticInit = []{return {2}::staticInit();}();

]=])

  string(REGEX REPLACE "{2}" "${f}" out_cpp_text "${out_cpp_text}")

  # message(STATUS "out_cpp_text: ${out_cpp_text}")
  file(APPEND tp_static_init.cpp "${out_cpp_text}")

endforeach()

